[package]
name = "heimdall-common"
description = "Commonly used resources for heimdall modules."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
exclude.workspace = true

[dependencies]
async-openai = "0.10.0"
clap = { version = "3.1.18", features = ["derive"] }
clap-verbosity-flag = "1.0.0"
colored = "2"
crossbeam-channel = "0.5.7"
ethers = "2.0.4"
fancy-regex = "0.11.0"
heimdall-cache = { path = "./../cache" }
indicatif = "0.17.0"
lazy_static = "1.4.0"
rand = "0.8.5"
reqwest = { version = "0.11.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
strsim = "0.10.0"
async-recursion = "1.0.5"
async-trait = "0.1.51"
chrono = "0.4.31"
backoff = { version = "0.4.0", features = ["tokio"] }
thiserror = "1.0.50"
tracing = "0.1.40"
